services:
  redis:
    image: redis:8.0.1
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - my-network

volumes:
  redis_data:

networks:
  my-network:
    driver: bridge